anikans/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('journal/', include('journal.urls', namespace='journal')),
]

journal/urls.py
from django.urls import path

from journal import views

app_name = 'journal'

urlpatterns = [
    path('history/', views.history_view, name='history'),
    
    path('adding/', views.adding_view, name='adding'),
    path('adding-remove/', views.remove_from_adding, name='remove_from_adding'),
    path('adding-confirm/', views.adding_confirm, name='adding_confirm'),

    path('sales/', views.sales_view, name='sales'),
    path('sales-remove/', views.remove_from_sales, name='remove_from_sales'),
    path('sales-confirm/', views.sales_confirm, name='sales_confirm'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_to_list/', views.add_to_list, name='add_to_list'),
]

main/views.py
from django.shortcuts import render
from django.db.models import Q, CharField
from django.db.models.functions import Cast
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from goods.models import Categories, Titles, Heroes, Products
from journal.models import Supplies, Sales


def index(request):
    
    category_id = request.GET.get('category')
    title_id = request.GET.get('title')
    hero_id = request.GET.get('hero')
    barcode = request.GET.get('barcode')
    audit = request.GET.get('checkboxAudit') is not None
    products = []
    
    if 'search' in request.GET:
        products = Products.objects.all()

        if category_id:
            products = products.filter(category_id=category_id)
        if title_id:
            products = products.filter(hero__title_id=title_id)
        if hero_id:
            products = products.filter(hero_id=hero_id)
        if barcode:
            products = products.annotate(
                item_str=Cast('item', CharField()),
                description_str=Cast('description', CharField())
            )
            products = products.filter(
            Q(barcode__endswith=barcode) | 
            Q(item_str__iendswith=barcode.lower()) | 
            Q(description_str__icontains=barcode.lower())
            )
        if audit:
            products = products.filter(quantity__lt=0)

    context = {
        'categories': Categories.objects.all(),
        'titles': Titles.objects.all(),
        'heroes': Heroes.objects.all(),
        'products': products,
    }
    return render(request, 'main/index.html', context)


@csrf_exempt
def add_to_list(request):
    item_id = request.POST.get('item_id')
    item = Products.objects.get(id=item_id)
    quantity = request.POST.get('quantity')
    to_list = request.POST.get('to_list')
    if to_list == "Supplies":
        cart_item, created = Supplies.objects.get_or_create(product=item)
        cart_item.quantity += int(quantity)
        cart_item.save()
    if to_list == "Sales":
        cart_item, created = Sales.objects.get_or_create(product=item)
        cart_item.quantity += int(quantity)
        cart_item.save()
    return JsonResponse({'status': 'success'})

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "css/bootstrap/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/index_css.css" %}>
    <link rel="apple-touch-icon" sizes="180x180" href={% static "favicon/apple-touch-icon.png" %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static "favicon/favicon-32x32.png" %}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static "favicon/favicon-16x16.png" %}>
    <link rel="manifest" href={% static "favicon/site.webmanifest" %}>
    <title>AniKans</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand bg-dark" 
            style="position: fixed; width: 100%; top: 0;" data-bs-theme="dark">
            <div class="container-fluid collapse navbar-collapse" id="navbarSupportedContent">
            <a class="navbar-brand" href={% url "main:index" %} title="Главная">AniKans</a>
                <form action="{% url "main:index" %}" method="GET" 
                    class="navbar-nav me-auto" style="height: 32px;">
                    <select class="form-select-sm" style="width: 130px;" id="category-select" name="category">
                        <option selected value="">---Категория---</option>
                        {% for el in categories %}
                            <option value={{ el.id }}>{{ el.name }}</option>
                        {% endfor %}
                    </select>
                    <div>
                        <a class="ms-2 mt-1" style="color: white">Игры</a>
                        <input id="is_game" class="ms-1 mt-2" type="checkbox" name="checkboxGames" value="false" onchange="filterTitles()">
                    </div>
                    <select class="form-select-sm ms-2" style="width: 130px;" id="title-select" name="title" onchange="filterHeroes()">
                        <option class="anime-title" value="">---Тайтл---</option>
                        {% for el in titles %}
                            <option class="anime-title" value={{ el.id }} data-game="{{ el.game|yesno:"true,false" }}">{{ el.name }}</option>
                        {% endfor %}
                    </select>
                    <select class="form-select-sm ms-2" style="width: 130px;" id="hero-select" name="hero">
                        <option class="anime-heroes" value="">---Персонаж---</option>
                        {% for el in heroes %}
                            <option class="anime-heroes" value={{ el.id }} data-title={{ el.title.id }}>{{ el.name }}</option>
                        {% endfor %}
                    </select>
                    <div class="d-flex">
                        <input id="audit" class="ms-2" type="checkbox" title="Недостачи" name="checkboxAudit" value="">
                        <input id="barcode-input" class="form-control ms-2" style="width: 110px;" type="text" size="13" name="barcode"
                            placeholder="Штрих-код" oninput="this.value = this.value.slice(0, 13)" aria-label="barcode-input">
                        <button class="btn btn-outline-success text-white ms-2 px-0 py-0" type="submit" name="search"
                            style="height: 32px; width: 40px;">
                            <img src= {% static "icons/search-white.svg" %} title="Поиск" alt="Search Icon" 
                                width="24" height="24">
                        </button>
                    </div>
                </form>
                <script>
                    function filterTitles() {
                        const isGameChecked = document.getElementById('is_game').checked;
                        const titleItems = document.querySelectorAll('.anime-title');
            
                        titleItems.forEach(title => {
                            const isGame = title.getAttribute('data-game') === 'true';
                            if (isGameChecked) {
                                title.style.display = isGame ? 'list-item' : 'none';
                            } else {
                                title.style.display = isGame ? 'none' : 'list-item';
                            }
                        });
                    }
                    window.onload = filterTitles;


                    function filterHeroes() {
                        const titleSelect = document.getElementById('title-select');
                        const selectedTitle = titleSelect.value;
                        const heroSelect = document.getElementById('hero-select');
                        const heroes = [
                            {% for el in heroes %}
                            {
                                id: "{{ el.id }}",
                                name: "{{ el.name }}",
                                titleId: "{{ el.title.id }}"
                            } {% if not forloop.last %},{% endif %}
                            {% endfor %}
                        ];
                        heroSelect.innerHTML = '<option class="anime-heroes" value="">---Персонаж---</option>';
                        
                        if (selectedTitle) {
                            heroes.forEach(hero => {
                                const title_id = hero['titleId'];
                                if (title_id == selectedTitle) {
                                    const option = document.createElement('option');
                                    option.value = hero['id'];
                                    option.textContent = hero['name'];
                                    heroSelect.appendChild(option);
                                }
                            });
                        }
                    }
                </script>
                <div class="navbar-nav d-flex jystify-content-end ms-2 mb-1" style="height: 32px;">
                    <a href={% url "journal:adding" %}>
                        <button type="button" class="btn btn-dark btn-secondary btn-sm" id="addingButton"
                            aria-expanded="false">
                            <img src= {% static "icons/plus-00be14.svg" %} title="Пополнение товара" alt="Adding Icon" 
                                width="24" height="24">
                            <span id="adding">00</span>
                        </button>
                    </a>
                    <a href={% url "journal:sales" %}>
                        <button type="button" class="btn btn-dark btn-secondary btn-sm" id="salesButton"
                            aria-expanded="false">
                            <img src= {% static "icons/basket-00be14.svg" %} title="Список продаж" alt="Sales Icon" 
                                width="24" height="24">
                            <span id="sales">00</span>
                        </button>
                    </a>
                    <a href={% url "journal:history" %}>
                        <button type="button" class="btn btn-dark btn-secondary btn-sm" id="historyButton"
                            aria-expanded="false">
                            <img src= {% static "icons/history-white.svg" %} alt="History Icon" 
                                width="24" height="24">
                        </button>
                    </a>
                    <a href={% url "admin:index" %}>
                        <button type="button" class="btn btn-dark btn-secondary btn-sm" id="loginButton"
                            aria-expanded="false">
                            <img src= {% static "icons/login-green-00be14.svg" %} alt="Login Icon" 
                                width="24" height="24">
                        </button>
                    </a>
                </div>
            </div>
        </nav>
    </header>
        <!-- Content on Page -->
    <section>
        <div class="container-fluid position-static" style="margin-top: 56px;">
            <div class="row mt-1">
                <div><!-- Left Sidebar --></div>
                <div id="contentOnPage" class="col-12">
                    <div>
                    {% block content %}
                    {% endblock %}
                    </div>
                </div>
                <div><!-- Rigft Sidebar --></div>
            </div>
        </div>
    </section>
    <script src={% static "js/bootstrap/bootstrap.bundle.min.js" %}></script>
</body>

</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<h2 class="no-print mt-2" style="text-align: center;">Товары по фильтрам
  <button onclick="printDiv('contentOnPage')" type="button" class="btn btn-light btn-secondary btn-sm" id="printButton"
  aria-expanded="false" >Печать</button>
</h2>
<table class="grid-table">
  <thead>
    <tr>
      <th scope="col" class="category-name">Категория</th>
      <th scope="col" class="title-name">Тайтл</th>
      <th scope="col" class="hero-name">Персонаж</th>
      <th scope="col" class="barcode-name">Штрих-код</th>
      <th scope="col" class="price-name">Цена</th>
      <th scope="col" class="quantity-name">Кол-во</th>
      <th scope="col" class="butt-on no-print">Оформить</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr class="table-item" data-id="{{ product.id }}">
      <td class="category-name">{{ product.category.name }}</td>
      <td class="title-name">{{ product.hero.title.name }}</td>
      <td class="hero-name">{{ product.hero.name }}</td>
      <td class="barcode-name">
        <div class="accordion" id="accordion{{ forloop.counter }}">
          <div class="accordion-item">
            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
              <button class="accordion-button collapsed pb-1 px-2" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" 
                aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                <p style="text-align: right; white-space: nowrap;">{{ product.readable_barcode }}<br><span style="color: gray;">{{ product.item }}</span></p>
              </button>
            </h2>
            <div class="accordion-collapse collapse" id="collapse{{ forloop.counter }}" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordion{{ forloop.counter }}">
              <div class="accordion-body">{{ product.description }}</div>
            </div>
          </div>
        </div>
      </td>
      <td class="price-name">{{ product.price }} ₽</td>
      <td class="quantity-name">{{ product.quantity }} шт.</td>
      <td class="butt-on no-print">
        <div class="button-container d-flex justify-content-start" data-product-id="product{{ product.id }}">
          <button type="submit" name="checkout" value="Supplies" class="checkout btn btn-link btn-sm" id="addingButton{{ product.id }}"
            aria-expanded="false">
            {% csrf_token %}
            <img src= {% static "icons/plus-00be14.svg" %} title="Добавить в приход" alt="Adding Icon" 
              width="24" height="24">
          </button>
          <input type="number" name="quantity_{{ product.id }}" value="1" min="0" max="9999"
            class="quantity" style="width: 50px; height: 20px; margin-bottom: 0;">
          <button type="submit" name="checkout" value="Sales" class="checkout btn btn-link btn-sm" id="salesButton{{ product.id }}"
            aria-expanded="false">
            {% csrf_token %}
            <img src= {% static "icons/basket-00be14.svg" %} title="Добавить в корзину" alt="Sales Icon" 
              width="24" height="24">
          </button>
        </div>
      </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="7" style="text-align: center;">Настройте фильтры</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  function printDiv(divId) {
    var printContent = document.getElementById(divId).innerHTML;
    var originalContent = document.body.innerHTML;
    document.body.innerHTML = printContent;
    window.print();
    document.body.innerHTML = originalContent;
  }
</script>

<script src={% static "js/jquery/jquery-3.7.0.min.js" %}></script>
<script src={% static "js/jquery-index.js" %}></script>
{% endblock %}